---
- name: Nested variables
  hosts: localhost
  gather_facts: false
  vars:
    fruit_basket:
      - name: A
        fruits:
          - apple
          - orange
      - name: Z
        fruits:
          - kiwi
          - grapes
  tasks:
    - name: Printing entire variable
      debug:
        var: fruit_basket
